const STRIPE_PUBLISHABLE_KEY = 'pk_test_86lwwdfZzvZEwdziYQQuZvVY000eaeQdDf';
const STRIPE_SECRET_KEY = 'sk_test_TjKyrQkUUknGVTgXRhFyGgZS00eMv0kO65';

module.exports = { STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY }